title: "Programando a Pasitos"
tagline: "No es un bug, es una característica no documentada"
description: "Blog de programación por Inazio Claver"
author:
  name: Inazio Claver
  url: https://github.com/inazense

url: "https://inazense.github.io"
baseurl: ""

lang: es
timezone: Europe/Madrid

permalink: /posts/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: "pages"
    values:
      layout: "page"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap

logo: /img/profile.png

paginate: 10
paginate_path: "/page/:num/"

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

include:
  - pages

feed:
  path: feed.xml

giscus:
  repo: inazense/inazense.github.io
  repo_id: R_kgDOSCW1ng
  category: General
  category_id: DIC_kwDOSCW1ns4C6-xJ
  mapping: pathname
  reactions_enabled: "1"
  input_position: bottom
  lang: es
